apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: stackdriver-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: stackdriver-agent
  template:
    metadata:
      labels:
        app: stackdriver-agent
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: NoSchedule
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - name: stackdriver-agent
        image: poeyashi/stackdriver-agent:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt/proc
          name: procmnt
        env:
          - name: MONITOR_HOST
            value: "true"
        resources:
          requests:
            cpu: 25m
            memory: 128Mi
          limits:
            cpu: 25m
            memory: 256Mi
      volumes:
      - name: procmnt
        hostPath:
          path: /proc
